--Q2-1. 테이블 - 외래 키 - 널(NULL)
--Q2-2. 문자열 - 문자셋
--Q2-3. VARCHAR2 - CHAR
--Q2-4. 제약조건 - 기본키 - 외래키
--Q2-5. 무결성(Integrity) - (개체) 무결성 - (참조) 무결성
--Q2-6. Unique + Not null + Index
--실습과제 1-1 (1)오라클 SQL
SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.SAL 
FROM EMP e , DEPT d 
WHERE E.DEPTNO =D.DEPTNO 
AND SAL > 2000;

--실습과제 1-1 (2)표준 SQL
SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.SAL 
FROM EMP e JOIN DEPT d 
		   ON (E.DEPTNO = D.DEPTNO)
WHERE SAL > 2000;

--실습과제 1-2
SELECT E.DEPTNO
	  ,D.DNAME
	  ,ROUND(AVG(E.SAL)) AS AVG_SAL
	  ,MAX(E.SAL) AS MAX_SAL
	  ,MIN(E.SAL) AS MIN_SAL
	  ,COUNT(E.DEPTNO) AS CNT
FROM EMP e , DEPT d 
WHERE E.DEPTNO = D.DEPTNO 
GROUP BY E.DEPTNO , D.DNAME;
;

--실습과제 2-3
SELECT D.DEPTNO 
	  ,D.DNAME 
	  ,E.EMPNO
	  ,E.ENAME 
	  ,E.JOB 
	  ,E.SAL 
FROM EMP e , DEPT d 
WHERE E.DEPTNO(+) = D.DEPTNO 
;

--실습과제 2-4
SELECT D.DEPTNO
	  ,D.DNAME
	  ,E.EMPNO
	  ,E.ENAME
	  ,E.MGR 
	  ,E.SAL 
	  ,E.DEPTNO 
	  ,S.LOSAL 
	  ,S.HISAL 
	  ,S.GRADE 
	  ,E2.EMPNO AS MGR_EMPNO
	  ,E2.ENAME AS MGR_ENAME
FROM EMP e , DEPT d , SALGRADE s , EMP e2 
WHERE E.DEPTNO(+) = D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL (+)
AND E.MGR = E2.EMPNO(+)
ORDER BY D.DEPTNO , E.EMPNO
;

--실습과제 210P (1)

SELECT E.JOB 
	  ,E.EMPNO
	  ,E.ENAME
	  ,E.SAL 
	  ,D.DEPTNO 
	  ,D.DNAME 
FROM EMP e ,DEPT d 
WHERE D.DEPTNO = E.DEPTNO 
AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN')
;

--실습과제 210P (2)

SELECT AVG(SAL) FROM EMP

SELECT E.EMPNO
	  ,E.ENAME 
	  ,D.DNAME 
	  ,E.HIREDATE 
	  ,D.LOC 
	  ,E.SAL 
	  ,S.GRADE 
FROM EMP e, DEPT d , SALGRADE s 
WHERE D.DEPTNO = E.DEPTNO 
AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+) 
AND E.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO
;

--실습과제 210P (3)

SELECT DISTINCT JOB FROM EMP WHERE DEPTNO = 30;
SELECT * FROM EMP WHERE DEPTNO = 10;

SELECT E.EMPNO 
	  ,E.ENAME 
	  ,E.JOB 
	  ,D.DEPTNO 
	  ,D.DNAME 
	  ,D.LOC 
FROM EMP e , DEPT d 
WHERE D.DEPTNO = E.DEPTNO 
AND JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = 30)
AND D.DEPTNO = 10;

--실습과제 210P (4)

SELECT E.EMPNO 
	  ,E.ENAME 
	  ,E.SAL 
	  ,S.GRADE
FROM EMP e , DEPT d , SALGRADE s 
WHERE D.DEPTNO = E.DEPTNO 
AND E.SAL BETWEEN S.LOSAL (+) AND S.HISAL (+)
AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY EMPNO
;

--실습과제 210P (5)

SELECT E.EMPNO 
	  ,E.ENAME 
	  ,E.SAL 
	  ,S.GRADE
FROM EMP e , DEPT d , SALGRADE s 
WHERE D.DEPTNO = E.DEPTNO 
AND E.SAL BETWEEN S.LOSAL (+) AND S.HISAL (+)
AND SAL > ALL(SELECT SAL FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY EMPNO
;
